### ISSUE TITLE
Also having trouble running this...

### ISSUE THREAD

**Issue by pavoni** [maddox/itunes-api#15]
I couldn.t install previously - so looking better but now get an error on running.

```
script/BOOTSTRAP
Finished setting up itunes-api! run it with script/server or install it with script/install.
````
````
$ script/server
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
module.js:328
    throw err;
    ^
Error: Cannot find module '/Users/.../itunes-api/node_modules/local-itunes/node_modules/osascript'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/gregdowling/itunes-api/app.js:9:17)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
error: Forever detected script exited with code: 1
````

**Comment by maddox** [comment]
try running `npm install`

**Comment by pavoni** [comment]
Thanks - this was the result
````
$ npm install
$ script/server
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
module.js:328
    throw err;
    ^

Error: Cannot find module '/Users/gregdowling/itunes-api/node_modules/local-itunes/node_modules/osascript'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/gregdowling/itunes-api/app.js:9:17)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
error: Forever detected script exited with code: 1
````

**Comment by maddox** [comment]
It looks like your `local-itunes` package can't be found. 

Delete your `node_modules` directory and run `npm install` again. It needs to have all the dependencies declared in `packages.json`

**Comment by pavoni** [comment]
Grateful for the help.

I deleted the whole tree - and cloned again.

I then ran script/bootstrap, which ran fine.

I then tried script/server with the same result as above.

I then did `rm -rf /Users/gregdowling/itunes-api/node_modules` and `npm install`

The result is, I think, the same.

````
$ script/server
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
module.js:328
    throw err;
    ^

Error: Cannot find module '/Users/gregdowling/itunes-api/node_modules/local-itunes/node_modules/osascript'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/gregdowling/itunes-api/app.js:9:17)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
error: Forever detected script exited with code: 1

**Comment by maddox** [comment]
I just cloned down `itunes-api` and bootstrapped it and all the modules installed fine, and it ran fine too.

Are you in the actual itunes-api directory? I manually deleted `local-itunes` from `node_modules` and my error was actually different than yours. It doesn't show the full path like your error did. I'm using node `0.12.2`.

```
⚡  script/server
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
module.js:338
    throw err;
          ^
Error: Cannot find module 'local-itunes'
```

**Comment by pavoni** [comment]
I was in the 'itunes-api` directory.

Just uninstalled and re-installed node. Not sure what matches your version.

````
$ node --version
v5.3.0
$ npm -version
3.3.12
``

**Comment by maddox** [comment]
i'm personally just using `0.12.2` lol. When you run `nam install` what kind of output do you get. does it mention installing `local-itunes`? I'm running out of ideas here, lol.

**Comment by pavoni** [comment]
I did a clean install of itunes-api - which gave this:-
````
$ npm install 
itunes-api@1.5.1 /Users/gregdowling/itunes-api
├─┬ body-parser@1.15.0 
│ ├── bytes@2.2.0 
│ ├── content-type@1.0.1 
│ ├─┬ debug@2.2.0 
│ │ └── ms@0.7.1 
│ ├── depd@1.1.0 
│ ├─┬ http-errors@1.4.0 
│ │ ├── inherits@2.0.1 
│ │ └── statuses@1.2.1 
│ ├── iconv-lite@0.4.13 
│ ├─┬ on-finished@2.3.0 
│ │ └── ee-first@1.1.1 
│ ├── qs@6.1.0 
│ ├─┬ raw-body@2.1.5 
│ │ └── unpipe@1.0.0 
│ └─┬ type-is@1.6.11 
│   ├── media-typer@0.3.0 
│   └─┬ mime-types@2.1.10 
│     └── mime-db@1.22.0 
├─┬ express@4.13.4 
│ ├─┬ accepts@1.2.13 
│ │ └── negotiator@0.5.3 
│ ├── array-flatten@1.1.1 
│ ├── content-disposition@0.5.1 
│ ├── cookie@0.1.5 
│ ├── cookie-signature@1.0.6 
│ ├── escape-html@1.0.3 
│ ├── etag@1.7.0 
│ ├── finalhandler@0.4.1 
│ ├── fresh@0.3.0 
│ ├── merge-descriptors@1.0.1 
│ ├── methods@1.1.2 
│ ├── parseurl@1.3.1 
│ ├── path-to-regexp@0.1.7 
│ ├─┬ proxy-addr@1.0.10 
│ │ ├── forwarded@0.1.0 
│ │ └── ipaddr.js@1.0.5 
│ ├── qs@4.0.0 
│ ├── range-parser@1.0.3 
│ ├─┬ send@0.13.1 
│ │ ├── destroy@1.0.4 
│ │ ├── http-errors@1.3.1 
│ │ └── mime@1.3.4 
│ ├── serve-static@1.10.2 
│ ├── utils-merge@1.0.0 
│ └── vary@1.0.1 
├─┬ local-itunes@0.3.0 
│ ├── neo-async@1.7.2 
│ ├─┬ osascript@1.2.0 
│ │ └── duplex-child-process@0.0.5 
│ └── require-dir@0.3.0 
├─┬ morgan@1.7.0 
│ ├── basic-auth@1.0.3 
│ └── on-headers@1.0.1 
├── osa@2.2.0 
└── parameterize@0.0.7 
````

**Comment by maddox** [comment]
It looks like it's installing.

So, I'm doing some manually loading of that lib [here](https://github.com/maddox/itunes-api/blob/master/app.js#L9). This must just be failing for you for some reason. It's probably a terrible way to be doing this anyways. I'm open to any suggestions or pull requests on doing it better.

**Comment by pavoni** [comment]
Don't know much about node I'm afraid!

I hacked the line to just load the library without a path - which stops the error.

However it then doesn't run a webserver on :8282 - so I guess it's not working.

Thanks for trying!

**Comment by pavoni** [comment]
Just added a port variable - and it's now running.

Wonder if they changed the port defaults
.
I expect there was a good reason you didn't do this to start with - but this is what I now have is.
````
var osascript = require('osascript')
// var osascript = require(path.join(__dirname, 'node_modules', 'local-itunes', 'node_modules', 'osascript'))
````

**Comment by pavoni** [comment]
Thanks!
<img width="366" alt="screen shot 2016-02-19 at 18 06 43" src="https://cloud.githubusercontent.com/assets/4487313/13184406/885e0c2a-d733-11e5-92ad-0766e8ab7eee.png">

**Comment by maddox** [comment]
Nice!

Ha, i think i tried that and it didn't work? I don't know. Feel free to open a pull request the correct it!

**Comment by pavoni** [comment]
Happy to - will leave the testing on old node versions to you :-)
