### ISSUE TITLE
Install on OSX with OSX Server running?

### ISSUE THREAD

**Issue by jjpeet** [maddox/itunes-api#21]
Hi,
I've just installed CodeJS and itunes-api and it doesn't seem t be working.
When I hit localhost:8181 from a browser (to check it's working)  I get nothing...  Should I be getting anything.

I'm running Mavericks & OSX Server with Web sites enabled in the server console.

Also, where might I find the logs?

Thx
JP

**Comment by maddox** [comment]
try running with just `script/server` to get logs. Also if you `script/install`, you should find logs in the logs directory.

**Comment by jjpeet** [comment]
Thanks for that - when I run script/server (with and without sudo) I get the following;
```
jjpeet:iTunes-API james$ sudo script/server
Password:
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
error: Could not read .foreverignore file.
error: ENOENT: no such file or directory, open '/Users/james/iTunes-API/.foreverignore'
module.js:327
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/james/iTunes-API/app.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
error: Forever detected script exited with code: 1
```

Also, I found the log file in ~/.forever/itunes-api.log and it has this in it;
```
jjpeet:.forever james$ tail itunes-api.log 
      ^

Error: ENOENT: no such file or directory, open 'log/logs.log'
    at Error (native)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'log/logs.log'
    at Error (native)
```
Any thoughts?
JP

**Comment by maddox** [comment]
Is there a `logs` dir in the `itunes-api` dir?

If not, try making one first and then starting the server.

**Comment by sudarshan367** [comment]
hi,
Is there an itunes api to use on windows ??

**Comment by maddox** [comment]
Sorry no, iTunes API uses AppleScript, which isn't available on Windows.
