### ISSUE TITLE
cant get the install to work

### ISSUE THREAD

**Issue by riotm0de** [maddox/itunes-api#32]
Hi,

cant get it to work :(

Last login: Mon Nov 20 00:56:21 on ttys000
**xxxxxxx:itunes-api-master xxxxxxx$ sudo npm install forever -g**
/usr/local/bin/forever -> /usr/local/lib/node_modules/forever/bin/forever

> fsevents@1.1.3 install /usr/local/lib/node_modules/forever/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@9.2.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp) 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /usr/local/lib/node_modules/forever/node_modules/fsevents
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/forever/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/forever/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/forever/node_modules/fsevents
node-pre-gyp ERR! node -v v9.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/forever/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ forever@0.15.3
added 116 packages and updated 1 package in 4.894s
**xxxxxxx:itunes-api-master xxxxxxx$** 

=========

**xxxxxxx:itunes-api-master xxxxxxx$ cat /Users/xxxxxxx/Library/LaunchAgents/org.itunes-api.plist**
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>org.itunes-api</string>

    <key>EnvironmentVariables</key>
    <dict>
      <key>PATH</key>
      <string>/usr/local/bin/:/usr/bin:$PATH</string>
      <key>NODE_ENV</key>
      <string>production</string>
    </dict>

    <key>Program</key>
    <string>/Users/xxxxxxx/Downloads/itunes-api-master/script/server</string>

    <key>AbandonProcessGroup</key>
    <false/>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>

    <key>WorkingDirectory</key>
    <string>/Users/xxxxxxx/Downloads/itunes-api-master</string>

    <key>StandardErrorPath</key>
    <string>/Users/xxxxxxx/Library/Logs/itunes-api.log</string>

    <key>StandardOutPath</key>
    <string>/Users/xxxxxxx/Library/Logs/itunes-api.log</string>

  </dict>
</plist>

please help

**Comment by riotm0de** [comment]
okay "sudo script/bootstrap" made the trick ;)
